 function [A,hhb] = centering(M)
% Author: Marta Sanzari, sanzari@diag.uniroma1.it       
      
     %  M(abs(M)>0)=1;   %to avoid noise generated by possible resizing
       %[mm,nn] =size(M);
       %%translation to center
       [uB,vB] = find(M>0);
       mub =min(uB);  mvb =min(vB); 
       uB = uB-mub+1;
       vB = vB-mvb+1;
       mub =min(uB); Mub =max(uB); mvb =min(vB); Mvb =max(vB);
       sizeX = (Mub-mub)+1; sizeY = (Mvb-mvb)+1;
       A = zeros(sizeX,sizeY);
       hhb =  fromRC2H(uB,vB,sizeX);
       A(hhb) = 1; 
       A = blkdiag(zeros(10,10),A,zeros(10,10)); 
       hhb = find(A==1);
 end